name: Publish on GitHub

on: [workflow_dispatch]

env:                                              #Environment variables
  MINECRAFT_VERSION: 1.19.2
  JAVA_VERSION: 17
  MOD_VERSION: 1.0.0
  MOD_RELEASE_NAME: "DungeonFinder v1.0.0 for Minecraft 1.19.2"
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 17
          cache: "gradle"
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish on GitHub
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          github-tag: "mc${{env.MINECRAFT_VERSION}}-${{env.MOD_VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"
          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: release
          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"